### ISSUE TITLE
`applyForce` and `applyLocalForce` gives error

### ISSUE THREAD

**Issue by hazem3500** [pmndrs/use-cannon#205] opened 2021-06-14 16:20 UTC
Calling `applyForce` or `applyLocalForce` gives an error
```
Uncaught TypeError: Found non-callable @@iterator
    at self.onmessage (worker.js:273)
```

# Example
```jsx
function ScalableBall() {
  const [ref, api] = useSphere(() => ({
    mass: 1,
    args: 1,
    position: [0, 1, 0],
  }))


  function scale() {
    api.applyForce(new Vec3(5, 5, 5), new Vec3(0, -1, 0))
  }

  return (
    <mesh ref={ref} onClick={scale}>
      <sphereGeometry args={[1]} />
      <meshBasicMaterial color="blue" />
    </mesh>
  )
}
```

[Live Demo](https://codesandbox.io/s/use-cannon-applyforce-bug-report-7x775)
> See the console from the browser dev-tools

**Comment by stockHuman** [comment] 2021-06-14 17:52
Hey there, I can't reproduce this upon cleaning up your example (updating dependencies, etc), but the `world` is not defined error it later produced may be just fixed in master. Could you try that?

**Comment by drcmda** [comment] 2021-06-14 21:47
applyForce: (force: number[], worldPoint: number[]) => void

can it be you're feeding it classes?

**Comment by stockHuman** [comment] 2021-06-14 21:57
Oh, yeah, I should've said: I also passed number arrays.

**Closed** 2021-06-14 23:13 UTC
Labels: awaiting feedback

**Comment by calvind777** [comment] 2021-06-21 10:09
I'm also having this same issue (not with applyForce, with useSphere), when converting a functioning component that uses `useBox` to use `useSphere` instead. Will try to make a working example in a sandbox
